export const homeStrings = {
  featured: "Destaque",
  featuredRole: "carrossel",
  details: "Ver detalhes",
  openDetails: (title: string) => `Ver detalhes de ${title}`,
  previous: "Anterior",
  next: "Próximo",
  chapters: (count: number) => `${count.toLocaleString("pt-BR")} cap.`,
  complete: "Completa",
  reading: "Continue lendo",
  newChapters: "Capítulos novos",
  newChaptersHint: "A fonte publicou mais capítulos desde o seu download.",
  plusChapters: (count: number) => `+${count.toLocaleString("pt-BR")} capítulos`,
  forYou: "Para você",
  forYouHint: "Parecidos com seus favoritos e o que você está lendo.",
  becauseYouRead: (title: string) => `Porque você leu ${title}`,
  updated: "Atualizados agora",
  arrivals: "Recém-chegados",
  bestRated: "Mais bem avaliados",
  completeWorks: "Obras completas",
  seeAll: "Ver tudo",
  scrollBack: "Voltar",
  scrollForward: "Avançar",
  genres: "Explorar por gênero",
  genresHint: "Os gêneros com mais obras nas suas fontes.",
  works: (count: number) => `${count.toLocaleString("pt-BR")} ${count === 1 ? "obra" : "obras"}`,
  welcomeTip: "Os livros que você baixar aparecem aqui, com os capítulos novos. Dica: ⌘K busca em todo o acervo."
} as const;
