/** Labels for the Kindle page, pt-BR. */
export const kindlePageStrings = {
  statusLabel: "Status do Kindle",
  connected: "Conectado",
  disconnected: "Desconectado",
  genericDevice: "Kindle",
  noDevice: "Nenhum Kindle conectado",
  connectedDescription: "Pronto para receber livros. Os arquivos são convertidos para AZW3 e copiados para a pasta documents.",
  disconnectedDescription: "Conecte o Kindle via USB para enviar livros da sua biblioteca direto para o aparelho.",
  mountPath: "Pasta no aparelho",
  targetFormat: "Formato",
  converterMissing: "Conversor AZW3 indisponível",
  tipsHeading: "Como conectar",
  tips: [
    "Conecte o Kindle via USB e desbloqueie a tela.",
    "Se o Kindle perguntar, escolha o modo de transferência de arquivos.",
    "O app detecta o aparelho sozinho em alguns segundos."
  ],
  openLibrary: "Ver biblioteca",

  // Send flow
  pickHeading: "Escolha os livros",
  pickDescription: "Marque os livros da biblioteca que você quer levar para o Kindle.",
  searchLabel: "Buscar livros para enviar",
  searchPlaceholder: "Buscar por título",
  selectBook: (title: string) => `Selecionar ${title}`,
  selectAllVisible: "Selecionar visíveis",
  clearSelection: "Limpar seleção",
  noBooksTitle: "Nenhum livro para enviar",
  noBooksDescription: "Baixe livros em Buscar. Eles aparecem aqui para enviar ao Kindle.",
  noBooksAction: "Buscar novels",
  noMatch: "Nenhum livro corresponde à busca.",
  sendHeading: "Enviar ao Kindle",
  sendDescription: "Os livros são enviados na ordem da lista. Arraste para reordenar.",
  queueLabel: "Livros a enviar",
  formatLabel: "Formato de destino",
  formatHint: "Via USB o Kindle recebe AZW3, com capa e sumário.",
  emptyQueue: "Nenhum livro selecionado. Marque livros ao lado para montar o envio.",
  removeFromQueue: (title: string) => `Tirar ${title} do envio`,
  send: (count: number) => (count === 1 ? "Enviar 1 livro" : `Enviar ${count} livros`),
  sendIdle: "Enviar ao Kindle",
  sending: "Enviando…",
  overallProgress: "Progresso do envio",
  itemWaiting: "Aguardando",
  itemPreparing: "Convertendo para AZW3…",
  itemPreparingPercent: (percent: number) => `Convertendo para AZW3… ${Math.round(percent)}%`,
  itemDone: "Pronto",
  itemReady: (sizeMb: number) => `${sizeMb.toLocaleString("pt-BR")} MB · pronto para enviar`,
  itemProgress: (title: string) => `Progresso de ${title}`,
  selectedCount: (count: number) => (count === 1 ? "1 selecionado" : `${count} selecionados`)
} as const;
