import type { ActivityKind } from "../services/socialClient";

const plural = (count: number, one: string, many: string) => `${count.toLocaleString("pt-BR")} ${count === 1 ? one : many}`;

export const socialStrings = {
  title: "Amigos",
  buttonHint: (count: number) => plural(count, "novidade dos amigos", "novidades dos amigos"),
  searchPeople: "Buscar",
  searchPeopleLabel: "Buscar amigos e conversas",
  peopleLabel: "Amigos e conversas",
  conversations: "Conversas",
  recsRow: "Indicações",
  recsRowHint: (count: number) => (count ? plural(count, "livro novo de amigos", "livros novos de amigos") : "Livros que seus amigos indicaram"),
  requestsRow: "Pedidos de amizade",
  requestsRowHint: (incoming: string | undefined, outgoing: number) =>
    incoming ? `@${incoming} quer ser seu amigo` : plural(outgoing, "pedido enviado", "pedidos enviados"),
  sayHi: "Diga oi",
  noMatch: "Ninguém com esse nome na sua lista.",
  emptyTitle: "Leia junto com seus amigos",
  emptyDescription: "Adicione alguém pelo apelido para conversar, ver a estante e indicar leituras.",
  addFriend: "Adicionar amigo",
  welcomePick: "Escolha uma conversa na lista.",

  // Friends
  addTitle: "Adicionar amigo",
  addHint: "Digite o apelido exato. Ninguém aparece em buscas parciais, então só acha você quem sabe o seu.",
  yourNickname: "Seu apelido:",
  copy: "Copiar",
  copied: "Apelido copiado.",
  done: "Concluído",
  friendsSinceShort: (date: string) => `Amigos desde ${date}`,
  addLabel: "Apelido do amigo",
  addPlaceholder: "@apelido",
  lookup: "Procurar",
  sendRequest: "Enviar pedido",
  requestSent: (nickname: string) => `Pedido enviado para @${nickname}.`,
  nowFriends: (nickname: string) => `Você e @${nickname} agora são amigos.`,
  notFound: "Ninguém com esse apelido. Confira se está escrito exatamente igual.",
  alreadyFriends: "Vocês já são amigos.",
  rateLimited: "Muitos pedidos agora. Tente de novo mais tarde.",
  networkError: "Sem conexão com a conta Oghma. Tente de novo.",
  genericError: "Não deu certo. Tente de novo.",
  incoming: "Pedidos recebidos",
  outgoing: "Pedidos enviados",
  waiting: "Aguardando resposta",
  accept: "Aceitar",
  decline: "Recusar",
  cancelRequest: "Cancelar pedido",
  friendsList: (count: number) => (count ? plural(count, "amigo", "amigos") : "Amigos"),
  noFriendsTitle: "Nenhum amigo ainda",
  noFriendsDescription: "Adicione alguém pelo apelido para indicar leituras e conversar.",
  friendSince: (date: string) => `Amigos desde ${date}`,
  viewProfile: "Ver perfil",
  chat: "Conversar",
  unfriend: "Desfazer amizade",
  unfriendConfirm: (nickname: string) => `Desfazer a amizade com @${nickname}?`,
  unfriendDescription: "Vocês deixam de ver a estante um do outro e a conversa fica fechada. Dá para pedir de novo depois.",
  block: "Bloquear",
  blockNamed: (nickname: string) => `Bloquear @${nickname}`,
  blockConfirm: (nickname: string) => `Bloquear @${nickname}?`,
  blockDescription: "Vocês deixam de ser amigos, a pessoa não consegue achar você pelo apelido nem mandar mensagens.",
  friendMenu: (nickname: string) => `Ações para @${nickname}`,

  // Profile
  back: "Voltar",
  backToChat: "Conversa",
  message: "Mensagem",
  viewShelf: "Ver estante",
  recommendTo: "Indicar livro…",
  markRead: "Marcar como lida",
  profileHint: "Ver a estante",
  readingNow: "Lendo agora",
  reading: (title: string) => `Lendo ${title}`,
  stats: { shelf: "na estante", completed: "concluídos", rating: "nota média", common: "em comum com você" },
  youToo: "Você também tem",
  addShort: "Adicionar",
  openInLibrary: "Abrir",
  inCommon: (count: number) => (count ? `${plural(count, "obra", "obras")} em comum` : "Nenhuma obra em comum ainda"),
  hiddenLibrary: "Esta pessoa deixou a biblioteca só para ela.",
  emptyLibrary: "A estante está vazia.",
  shelfGroups: {
    reading: "Lendo",
    paused: "Pausados",
    completed: "Concluídos",
    dropped: "Abandonados",
    unread: "Na estante"
  } as Record<string, string>,
  open: "Abrir",
  addToLibrary: "Adicionar à biblioteca",
  inLibrary: "Na sua biblioteca",
  recommend: "Indicar",

  // Conversations
  chatsEmptyTitle: "Nenhuma conversa",
  chatsEmptyDescription: "Abra a conversa pelo perfil de um amigo ou indique um livro.",
  pickChat: "Escolha uma conversa",
  messagePlaceholder: "Mensagem",
  messageLabel: (nickname: string) => `Mensagem para @${nickname}`,
  send: "Enviar",
  attachBook: "Indicar um livro",
  attachFromLibrary: "Livro da biblioteca",
  attachFromLibraryHint: "Indicar algo que você já tem",
  attachFromCatalog: "Buscar no catálogo",
  attachFromCatalogHint: "Qualquer obra do Oghma",
  recommendationEyebrow: "Indicação",
  loadOlder: "Mensagens anteriores",
  you: "Você",
  youRecommended: "Você indicou",
  theyRecommended: "Indicou",
  chapters: (count: number) => plural(count, "cap.", "cap."),
  cancel: "Cancelar",
  pickedNames: (names: string[]) => (names.length > 2 ? `@${names[0]}, @${names[1]} e mais ${names.length - 2}` : names.map((name) => `@${name}`).join(" e ")),
  unread: (count: number) => plural(count, "mensagem nova", "mensagens novas"),
  bookMessage: "Indicou um livro",
  notFriendsAnymore: "Vocês não são mais amigos; a conversa está fechada.",

  // Recommendations
  recsNew: "Novas",
  recsAll: "Todas",
  recsFilterLabel: "Mostrar",
  recsEmptyTitle: "Nenhuma indicação",
  recsEmptyDescription: "Quando um amigo indicar um livro, ele aparece aqui.",
  recommendedBy: (nickname: string) => `@${nickname} indicou`,
  recommendedVerb: "indicou",
  alsoRead: (names: string[]) => `${names.map((name) => `@${name}`).join(", ")} também ${names.length > 1 ? "leram" : "leu"}`,
  markSeen: "Marcar como vista",
  pickLibrary: "Biblioteca",
  pickCatalog: "Catálogo",
  recsHeaderHint: "Livros que seus amigos acharam a sua cara",
  recsSeen: "Já vistas",
  noNote: "Sem recado",
  reply: "Responder",
  openInDiscover: "Abrir no Buscar",
  inYourLibrary: "Na biblioteca",
  added: "Adicionada",
  dismissed: "Dispensada",
  dismiss: "Dispensar",

  // Recommend dialog
  recommendTitle: "Indicar a um amigo",
  recommendAction: "Indicar para…",
  recommendPick: "Para quem",
  recommendEyebrow: "Indicar",
  recommendSearch: "Buscar amigo",
  recent: "Recentes",
  recommendNoteShort: "Adicionar um recado (opcional)",
  recommendNote: "Recado (opcional)",
  recommendNotePlaceholder: "Por que vale a leitura?",
  recommendSend: (count: number) => (count ? `Enviar para ${count}` : "Enviar"),
  recommendSent: (count: number) => (count > 1 ? `Indicação enviada para ${count} amigos.` : "Indicação enviada."),
  recommendNoFriends: "Adicione um amigo antes de indicar.",
  pickBookTitle: "Livro da biblioteca",
  pickBookSearch: "Buscar na sua biblioteca",
  pickCatalogTitle: "Buscar no catálogo",
  pickCatalogSearch: "Título ou autor",
  pickCatalogHint: "Digite para buscar em todas as fontes ativas.",
  pickNothing: "Nada encontrado.",
  pickFor: (nickname: string) => `Para @${nickname}`,

  // Activity
  activityTitle: "Atividade dos amigos",
  friendsReadingTitle: "Amigos estão lendo",
  friendsReadingMeta: (names: string[]) => (names.length > 1 ? `@${names[0]} e mais ${names.length - 1}` : `@${names[0]}`),
  seeFriends: "Ver Amigos",
  fromFriendsTitle: "Indicado por amigos",
  activity: (kind: ActivityKind, rating?: number | null) => {
    switch (kind) {
      case "started": return "começou a ler";
      case "finished": return rating ? `terminou · ${"★".repeat(rating)}` : "terminou";
      case "dropped": return "abandonou";
      case "rated": return `deu ${"★".repeat(rating ?? 0)} para`;
      default: return "adicionou à estante";
    }
  },

  // Privacy (Ajustes › Conta)
  privacyTitle: "Privacidade",
  privacyDescription: "O que seus amigos veem.",
  libraryVisible: "Amigos veem minha biblioteca",
  libraryVisibleHint: "Status, notas e favoritos dos livros. Livros marcados \"Só eu vejo\" ficam de fora.",
  activityVisible: "Mostrar minha atividade",
  activityVisibleHint: "Quando você começa, termina ou dá nota a um livro, seus amigos veem no Início.",
  privateBook: "Só eu vejo",
  privateBookOff: "Mostrar para amigos",
  privateBadge: "Só você vê este livro"
} as const;
